//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPCRUDFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AlumnosA
    {
        public int id { get; set; }

       //data notation para que valide en l servidor
        [Required]
        [Display(Name = "Ingrese Nombre")]
        public string Nombre { get; set; }
        [Required]
        [Display(Name = "Ingrese Apellido")]
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Sexo { get; set; }


        //lo agregue yo al nombre completo

        public string NombreCompleto { get { return Nombre + " " + Apellido; } }
    }
}
